apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: app-secret
  name: app-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-app-secret  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: app-secret1  ##KEY1
      secretKey: app-secret1 ##KEY1
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: store-app-secret
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-app-secret   ##The secret name in ocp that is stored in AWS Secret Manager
---
