apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
  name: store-app-secret
  namespace: app-secret  ##NAMESPACE $USER_NAMESPACE (The namespace where the OCP secret is going to be created in)
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa   ##The Service Account $SA_NAME that is going to have access to the ocp secret)
            namespace: app-secret
      region: us-east-1
      service: SecretsManager
