apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: db-secret
  name: db-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: osrosa-db-secret  ##The secret name in ocp that is stored in AWS Secret Manager
        metadataPolicy: None
        property: app-secret2  ##KEY1
      secretKey: app-secret2 ##KEY1
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: store-db-secret
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: osrosa-db-secret   ##The secret name in ocp that is stored in AWS Secret Manager
---
